### PR TITLE
CORE - Require latest stable drupal version

### PR DESCRIPTION
**Pull request by omarlopesino**
Currently, we require ^9 version of Drupal core.  This produces that when dependencies are installed, I get the latest version of the core. In this case, after installing composer packages I obtained the 9.2.x version, which is still a development version. 

The boilerplate should download a stable version to the packages to prevent unexpected bugs in versions that may not be stable enough.

This PR fixes the drupal version to 9.1. it will install Drupal 9.1.6. Please check, thanks!

### CODE REVIEW

**Comment by dlopez-akalam** [comment]
github is reporting there is no new line at the end of some files. Could you fix it? besides that, it looks good to me

**Comment by omarlopesino** [comment]
Thanks for noticing! Fixed, merging into 1.x.

**Comment by rsanzante** [comment]
Why spreading the git-ignored files on different files on each folder instead of having all ignored files in one place, the .gitignore in the root folder?

**Comment by omarlopesino** [comment]
@rsanzante  those changes are done after upgrading core-recommended, so I just trust that is a good choice.

I don't know the exact reason, but I guess it is done because it may be easier to maintain. Adding all the lines to the root folder may lead to removing the folders but not updating the git ignore, but with that solution the lines are removed automatically when the folder that contains those files will also remove the .gitignore.

**Pull request merged**
