### PR TITLE
Replaced ngrok with localtunnel

### PR DESCRIPTION
**Pull request by juanjol**
It seems ngrok now requires registration to use it, which makes it difficult to use on boilerplate. I suggest a tool change to localtunnel (https://github.com/localtunnel/localtunnel), which offers similar functionality in an open way.

I have generated the docker-compose.localtunnel.yml file with the localtunnel docker container, and replaced the ngrok commands to launch the tunnel correctly.

### CODE REVIEW

**Review by keopx — APPROVED** [review]
LGTM

Awesome!!!

**Comment by omarlopesino** [comment]
@Eduardo-Morales-Alberti  may you explain why have you marked the pull request as draft? It would be good a comment so if we review this PR after a long time we know why it is in draft. Thanks in advance.

**Comment by Eduardo-Morales-Alberti** [comment]
> @Eduardo-Morales-Alberti may you explain why have you marked the pull request as draft? It would be good a comment so if we review this PR after a long time we know why it is in draft. Thanks in advance.

@mistermoper Because after talking with @juanjol we decided that the PR is not ready to merge, and needs to be reviewed, refactor, tested, and checked. I did a test with the changes and I was not able to make it work.

**Comment by mistermoper** [comment]
@juanjol any advances on this?

**Comment by omarlopesino** [comment]
@juanjol any advances on this?

@Eduardo-Morales-Alberti when you say 'I was not able to make it work', what errors did you found? If you remember it would be grateful to know because it may help others to collaborate on moving forward this issue.

**Comment by keopx** [comment]
WIP

**Comment by Eduardo-Morales-Alberti** [comment]
@mistermoper I did the test a long time ago, I do not remember the problems that I found.
I recommend trying again it on a project and documenting the errors here.

**Pull request closed without merging**
